[supabase]
url = "https://phrkijmrwhqzmfxzlhee.supabase.co"
anon_key = "sb_publishable_NVg6FfqWNFFIGOluMP1j0Q_FKPtqlGG"

[auth.users.iragielis]
name = "Ira Gielis"
password = "T123"

[auth.users.valeriehufkens]
name = "Valerie Hufkens"
password = "fajwis-Wobdax-papti9"